<?php echo $this->doctype(); ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>News</title>
    <?php 
        $this->headLink()->appendStylesheet('/css/bootstrap.min.css');
        $this->headLink()->appendStylesheet('/css/bootstrap-responsive.min.css');

        $this->headScript()->appendFile('http://code.jquery.com/jquery-latest.js', 'text/javascript');
        $this->headScript()->appendFile('/js/bootstrap.min.js', 'text/javascript');

        echo $this->headLink();
        echo $this->headScript();
    ?>
</head>
<body>
<!-- NAVBAR
    ================================================== -->
    <div class="navbar-wrapper">
        <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
        <div class="container">

            <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                    <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index')); ?>">News</a>
                    <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li <?php if($this->title == 'news'):?>class="active"<?php endif;?>><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index')) ?>">Home</a></li>
                            <li <?php if($this->title == 'management'):?>class="active"<?php endif;?>><a href="<?php echo $this->url(array('controller'=>'management', 'action'=>'index')) ?>">Management</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div><!-- /.navbar-inner -->
            </div><!-- /.navbar -->

        </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
        <a id="top"></a>

        <!-- START THE FEATURETTES -->
        <?php echo $this->layout()->content; ?>
        <!-- /END THE FEATURETTES -->


        <!-- FOOTER -->
        <footer>
            <p class="pull-right"><a href="#top">Back to top</a></p>
            <p>&copy; 2013 Chuehnone &middot; </p>
        </footer>

    </div><!-- /.container -->
</body>
</html>